### ISSUE TITLE
Fix the link rendering in the authoring tool

### ISSUE THREAD

**Issue by rsg73626** [ecureuill/SELIProject#75]
The links added by one teacher in the authoring tool are not rendering correctly. 

## Expected Behavior

The links added by one teacher in the authoring tool must render correctly.

## Current Behavior

The links are not being rendered as links, but as texts (the <a> tag structure appears instead).

## Steps to Reproduce

Add a link in the authoring tool. Render this link.

**[SELI - Accessibility test](https://docs.google.com/presentation/d/1OBRtT9S3NZWK2bq9wvEzXLxcoQMxMC_CesAsUgqkUww/edit#slide=id.g656ec9906d_4_83) (slide 21)**

## Environment

Browser: all 

## Possible Solution

Camila already fixed it in her repo copy. Check and/or use this implementation.

## Related issues

https://github.com/ecureuill/SELIProject/issues/73

**Comment by ecureuill** [comment]
https://github.com/solex2006/SELIProject/issues/35
