### ISSUE TITLE
Adjust the quiz time functionality (remove or give more options to the users

### ISSUE THREAD

**Issue by rsg73626** [ecureuill/SELIProject#79]
For the prototype it was defined that the quizzes were not going to have time constraint.

## Expected Behavior

There must be an alternative to remove or adjust the time for people that need accessibility

## Current Behavior

The quiz time functionality does not provide an alternative to accessibility needs. 

## Steps to Reproduce

Use one quiz with time (student role).
Create one quiz (teacher role).

**[SELI - Accessibility test](https://docs.google.com/presentation/d/1OBRtT9S3NZWK2bq9wvEzXLxcoQMxMC_CesAsUgqkUww/edit#slide=id.g656ec9906d_4_41) (slide 27)**

## Environment

Browser: all

## Possible Solution

Remove the time constraint.
**Or** provide an alternative to teacher to adapt the time for the students that need accessibility.
**Or** provide an alternative to the students that need accessibility. 

## Related Issues

https://github.com/ecureuill/SELIProject/issues/80
https://github.com/ecureuill/SELIProject/issues/81

**Comment by ecureuill** [comment]
Precisa testar a função, eles trabalharam no requisito no início do ano

**Comment by ecureuill** [comment]
https://github.com/solex2006/SELIProject/issues/38
