### ISSUE TITLE
Adjust the implementation of the radio groups in the quiz by adding the adequate aria-attribute to support accessibility. 

### ISSUE THREAD

**Issue by rsg73626** [ecureuill/SELIProject#81]
It's necessary to adequate the radio groups to provide accessibility support. 

## Expected Behavior

Every radio group must provide a descriptive text informing what it is about.

## Current Behavior

The radio groups does not provide the adequate description for the accessibility support.

## Steps to Reproduce

Use a quiz. 

**[SELE - Accessibility test](https://docs.google.com/presentation/d/1OBRtT9S3NZWK2bq9wvEzXLxcoQMxMC_CesAsUgqkUww/edit#slide=id.g657da46494_0_12) (slide 29)**

## Environment

Browser: all 

## Possible Solution

Add the adequate aria attribute to the tags as indicated in the related slide. Check if it's possible to use some native HTML5 tag that could solve this problem (if so, use this alternative).

## Related issues

https://github.com/ecureuill/SELIProject/issues/79
https://github.com/ecureuill/SELIProject/issues/80

**Comment by ecureuill** [comment]
https://github.com/solex2006/SELIProject/issues/37
